name: Build and Release DMG

on:
  push:
    branches: [ main ]
  
  # Allow manual workflow dispatch
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        npm install
        cd frontend && npm install
        cd ../backend && pip install -r requirements.txt
        
    - name: Install PyInstaller
      run: |
        cd backend
        pip install pyinstaller
        
    - name: Build application
      run: npm run build:all
      
    - name: Package Electron app
      run: npm run dist:mac
      
    - name: Get version
      id: version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
        release_name: PR Monitor v${{ steps.version.outputs.VERSION }} Build ${{ github.run_number }}
        body: |
          ## PR Monitor Release
          
          **Version:** ${{ steps.version.outputs.VERSION }}
          **Build:** ${{ github.run_number }}
          **Commit:** ${{ github.sha }}
          
          ### Features in this release:
          - Visual navigation path system with light → dark color hierarchy
          - GitHub-style tray icons (🟢 green/🟡 yellow) for review status
          - Complete node labeling: T (teams), R (repositories), PR (pull requests)
          - Scrollable subscription lists
          - Enhanced WebSocket stability
          
          ### Installation:
          1. Download the DMG file below
          2. Open the DMG and drag PR Monitor to Applications
          3. Launch the app and enter your GitHub token
          
          **Note:** This is an unsigned application. On first launch, you may need to right-click and select "Open" or go to System Preferences > Security & Privacy to allow it to run.
        draft: false
        prerelease: false
        
    - name: Upload DMG to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/PR Monitor-${{ steps.version.outputs.VERSION }}-arm64.dmg
        asset_name: PR-Monitor-v${{ steps.version.outputs.VERSION }}-arm64.dmg
        asset_content_type: application/octet-stream
        
    - name: Upload ZIP to Release  
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/PR Monitor-${{ steps.version.outputs.VERSION }}-arm64-mac.zip
        asset_name: PR-Monitor-v${{ steps.version.outputs.VERSION }}-arm64.zip
        asset_content_type: application/zip